"""SQLite storage for FusionSolar historical data."""

from darb_solar.db.connection import (
    DEFAULT_DATA_DIR,
    DEFAULT_DB_PATH,
    DEFAULT_TIMEZONE_NAME,
    PROJECT_ROOT,
    get_connection,
    init_db,
    resolve_db_path,
)
from darb_solar.db.reads import (
    get_latest_collected_at,
    get_latest_plant_synced_at,
    get_plant,
    get_sync_window,
    list_device_power_readings,
    list_devices,
    list_plant_power_readings,
)
from darb_solar.db.time import utc_now_iso
from darb_solar.db.types import (
    Device,
    DevicePowerReading,
    DeviceRole,
    Plant,
    PlantPowerReading,
    SyncWindow,
    SyncWindowCheckpointStatus,
)
from darb_solar.db.writes import (
    upsert_device,
    upsert_device_power_reading,
    upsert_device_power_readings,
    upsert_devices,
    upsert_plant,
    upsert_plant_power_reading,
    upsert_plant_power_readings,
    upsert_plants,
    upsert_sync_window,
    upsert_sync_windows,
)

__all__ = [
    "DEFAULT_DATA_DIR",
    "DEFAULT_DB_PATH",
    "DEFAULT_TIMEZONE_NAME",
    "PROJECT_ROOT",
    "Device",
    "DevicePowerReading",
    "DeviceRole",
    "Plant",
    "PlantPowerReading",
    "SyncWindow",
    "SyncWindowCheckpointStatus",
    "get_connection",
    "get_latest_collected_at",
    "get_latest_plant_synced_at",
    "get_plant",
    "get_sync_window",
    "init_db",
    "list_device_power_readings",
    "list_devices",
    "list_plant_power_readings",
    "resolve_db_path",
    "upsert_device",
    "upsert_device_power_reading",
    "upsert_device_power_readings",
    "upsert_devices",
    "upsert_plant",
    "upsert_plant_power_reading",
    "upsert_plant_power_readings",
    "upsert_plants",
    "upsert_sync_window",
    "upsert_sync_windows",
    "utc_now_iso",
]
